# Generated by Django 4.2.6 on 2023-10-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishCars", "0002_postcar_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcar",
            name="type_car",
            field=models.CharField(
                choices=[
                    ("Crossover", "Crossover"),
                    ("Hatchback", "Hatchback"),
                    ("SUV", "SUV"),
                    ("Sedan", "Sedan"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
